### ISSUE TITLE
Firefox Quantum

### ISSUE THREAD

**Issue by Luee-maker** [Whonix/onion-grater#5]
Hello!
Ive seen your projects and Id really like it. I have a suggestion to you. I need maximize privacy and security level of Firefox Quantum users. If you are interesting in my project please text me as soon as possible.

**Comment by adrelanos** [comment]
Please elaborate.

**Comment by madaidan** [comment]
I'm not sure how this is relevant to onion-grater.

**Comment by adrelanos** [comment]
It's not indeed.
